title:              Arlington, MA Disability Commission
title_home:         Arlington, MA<br>Disability Commission
title_short:        Arlington Disability
email:              your-email@example.com
description:        
author:             Arlington MA Disability Commission
baseurl:            "/"
url:                "https://arlington-ma-disability-commission.github.io"

# Social Profiles
# twitter_username:   SBootstrap
# github_username:    StartBootstrap
# facebook_username:  ArlingtonMADisability
# instagram_username:  
# linkedin_username:
# town_site_url:      https://www.arlingtonma.gov/town-governance/boards-and-committees/disability-commission

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

sass:
  quiet_deps: true
  silence_deprecations:
    - import
    - global-builtin
    - color-functions
    - slash-div
    - if-function
